[build]
  base = ""
  publish = "public/"
  command = "npm run build"

[[redirects]]
  from = "https://taylorschapel.netlify.app/*"
  to = "https://taylorschapel.org/:splat"
  status = 301
  force = true

[context.production.environment]
  NODE_VERSION = "24.5.0"
  NPM_VERSION = "11.4.2"
  NODE_ENV = "production"
